name: Build docker image

on:
  push:
    branches:
      - main

permissions:
  contents: read
  id-token: write # required for keyless image signing via cosign (OIDC token to Sigstore)

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          persist-credentials: false
      -
        name: Login to Stackable Harbor
        uses: docker/login-action@dbcb813823bdd20940b903addbd779551569679f # v4.6.0
        with:
          registry: oci.stackable.tech
          username: robot$stackable+github-action-build
          password: ${{ secrets.HARBOR_ROBOT_STACKABLE_GITHUB_ACTION_BUILD_SECRET }}
      -
        name: Set up Cosign
        uses: sigstore/cosign-installer@6f9f17788090df1f26f669e9d70d6ae9567deba6 # v4.1.2
      -
        name: Build and push
        id: build-and-push
        uses: docker/build-push-action@53b7df96c91f9c12dcc8a07bcb9ccacbed38856a # v7.3.0
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: oci.stackable.tech/stackable/csaf_publisher:0.0.0-dev
          build-args: |
            REVISION=${{ github.sha }}
            VERSION=dev
      -
        name: Sign the published image
        env:
          DIGEST: ${{ steps.build-and-push.outputs.digest }}
        run: cosign sign -y oci.stackable.tech/stackable/csaf_publisher@"$DIGEST"
