name: Build docker image

on:
  push:
    branches:
      - main

permissions:
  id-token: write

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
      -
        name: Login to Stackable Harbor
        uses: docker/login-action@af1e73f918a031802d376d3c8bbc3fe56130a9b0 # v4.4.0
        with:
          registry: oci.stackable.tech
          username: robot$stackable+github-action-build
          password: ${{ secrets.HARBOR_ROBOT_STACKABLE_GITHUB_ACTION_BUILD_SECRET }}
      -
        name: Set up Cosign
        uses: sigstore/cosign-installer@6f9f17788090df1f26f669e9d70d6ae9567deba6 # v4.1.2
      -
        name: Build and push
        id: build-and-push
        uses: docker/build-push-action@53b7df96c91f9c12dcc8a07bcb9ccacbed38856a # v7.3.0
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: oci.stackable.tech/stackable/csaf_publisher:0.0.0-dev
          build-args: |
            REVISION=${{ github.sha }}
            VERSION=dev
      -
        name: Sign the published image
        run: cosign sign -y oci.stackable.tech/stackable/csaf_publisher@${{ steps.build-and-push.outputs.digest }}
